# Generated by Django 3.0.8 on 2020-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugapp', '0002_auto_20200804_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
